In [1]:
import numpy as np

Lecture 13 is a review for the 1st exam. Sort of wrap up.

5x3 U r = 3

N(U) = {[0/0/0]}

B = [U/2U] 

Reduced echelon form

[U/0]

r=3

C = [U,U/U,0]

-> [U,U/0,-U] - > [U,0/0,-U] -> [U,0/0,U]

r = r(U)x2 = 6

dim N(C.T) ?

C - 10x6 =>

dim N(C.T) = 10 - r = 6



Ax = [2/4/2]

x=[2/0/0]+c[1/1/0]+d[0/0/1]

A is 3x3

r = 1

dim N(A) = 2

A = [1,?,?/2,?,?/1,?,?]

A = [1,?,0/2,?,0/1,?,0]

A = [1,-1,0/2,-2,0/1,-1,0]





In [2]:
A = np.array([[1,-1,0],
              [2,-2,0],
              [1,-1,0]])

In [3]:
b = np.array([2,4,2])

In [4]:
np.dot(A,[2,0,0])

array([2, 4, 2])

In [5]:
np.dot(A,[1,1,0])

array([0, 0, 0])

In [6]:
np.dot(A,[0,0,1])

array([0, 0, 0])

Ax=b can be solved if b is in a columnspace. => b is a multiple of [1,2,1]

If N(A) is 0-vector and A is a square matrix (m=n) = > N(A.T) is 0-vector as well.

T or F B^2 = 0 => B=0 - F

e.g. B = [[0,1],
         [0,0]]

T or F nxn independent columns. Ax=b is always solvable - T
they form basis. Also A is invertible.

In [7]:
B = np.dot(np.array([[1,1,0],
              [0,1,0],
              [1,0,1]]),np.array([[1,0,-1,2],
                                 [0,1,1,-1],
                                 [0,0,0,0]]))

In [8]:
B.shape

(3, 4)

N(CD) = N(D) if C is invertible.

dim N(B)  = 2

min 33

In [9]:
B

array([[ 1,  1,  0,  1],
       [ 0,  1,  1, -1],
       [ 1,  0, -1,  2]])

If A and B same 4 subspaces then A = cB?
False

Example: A,B any invertible 6x6, but they are not the same.

If rows are exchanged, which subspaces are the same: RowSpace and the NullSpace

v = [1,2,3] can't be both in a NullSpace and be a row of A. Why not?

Av neq 0. Intersection of nullspace and rowspace is 0 vector, nullspace is perpendicular to rowspace.