In [2]:
import numpy as np

In [3]:
A =  np.array([[1,2,3],
                [4,5,11],
                [7,8,9]])
b = np.array([1,2,3])


A*X=B; X=inv(A)*B.

In [4]:
Ainv = np.linalg.inv(A)
Ainv

array([[-1.43333333,  0.2       ,  0.23333333],
       [ 1.36666667, -0.4       ,  0.03333333],
       [-0.1       ,  0.2       , -0.1       ]])

In [5]:
X = np.dot(Ainv,b)
X

array([-0.33333333,  0.66666667,  0.        ])

Let's check

In [6]:
np.dot(A,X)

array([ 1.,  2.,  3.])

Another method

In [7]:
X = np.linalg.solve(A,b)

Let's check

In [8]:
np.dot(A,X)

array([ 1.,  2.,  3.])

We must get Identity Matrix if we A*inv(A)

In [9]:
np.dot(Ainv,A)

array([[  1.00000000e+00,   0.00000000e+00,   4.44089210e-16],
       [  0.00000000e+00,   1.00000000e+00,  -6.66133815e-16],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

Let's also check determinant.

In [10]:
np.linalg.det(A)

29.999999999999989

Now let's try something else. Let's say transposing.

In [11]:
np.transpose(A)

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3, 11,  9]])

In [12]:
np.dot(np.transpose(A),np.transpose(Ainv))

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  4.44089210e-16,  -6.66133815e-16,   1.00000000e+00]])

Maybe Elimination Matrix now?

In [13]:
Ab = np.c_[A,b]
Ab

array([[ 1,  2,  3,  1],
       [ 4,  5, 11,  2],
       [ 7,  8,  9,  3]])

In [14]:
Id = np.identity(3)
Id

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [15]:
E21 = np.array([[1,0,0],
               [-4,1,0],
               [0,0,1]])


In [16]:
Ab2 = np.dot(E21,Ab)
Ab2

array([[ 1,  2,  3,  1],
       [ 0, -3, -1, -2],
       [ 7,  8,  9,  3]])

In [17]:
E31 = np.array([[1,0,0],
                [0,1,0],
                [-7,0,1]])

In [18]:
Ab3 = np.dot(E31,Ab2)
Ab3

array([[  1,   2,   3,   1],
       [  0,  -3,  -1,  -2],
       [  0,  -6, -12,  -4]])

In [19]:
E32 = np.array([[1,0,0],
               [0,1,0],
               [0,-2,1]])

In [20]:
Ab4 = np.dot(E32,Ab3)
Ab4

array([[  1,   2,   3,   1],
       [  0,  -3,  -1,  -2],
       [  0,   0, -10,   0]])

In [21]:
X = np.array([(Ab4[0,3]-Ab4[0,2]*Ab4[2,3]/Ab4[2,2]-Ab[0,1]*(Ab4[1,3]-Ab4[1,2]*Ab4[2,3]/Ab4[2,2])/Ab4[1,1])/Ab[0,0],
             (Ab4[1,3]-Ab4[1,2]*(Ab4[2,3]/Ab4[2,2]))/Ab4[1,1],
             Ab4[2,3]/Ab4[2,2]])
X

array([-0.33333333,  0.66666667, -0.        ])

E32*E31*(E21*A)

In [22]:
E=np.dot(E32,np.dot(E31,E21))
E

array([[ 1,  0,  0],
       [-4,  1,  0],
       [ 1, -2,  1]])

In [33]:
U = np.dot(E,A)
U

array([[  1,   2,   3],
       [  0,  -3,  -1],
       [  0,   0, -10]])

Permutation Matrices, needed to exchange rows if element on pivot position is 0.

In [24]:
P1 = np.array([[1,0,0],
           [0,0,1],
           [0,1,0]])

P2 = np.array([[0,1,0],
           [1,0,0],
           [0,0,1]])

P3 = np.array([[0,1,0],
               [0,0,1],
               [1,0,0]])

P4 = np.array([[0,0,1],
              [1,0,0],
              [0,1,0]])

P5 = np.array([[0,0,1],
              [0,1,0],
              [1,0,0]])

P6 = Id

Some properties of permutation matrices: inv(P) = transpose(P) => P*transpose(P) = Id

In [30]:
np.dot(P1,np.transpose(P1))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Change rows 2 and 3 of A matrix

In [29]:
np.dot(P1,A)

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [ 4,  5, 11]])

A = LU; L = (U^-1)A

In [38]:
L = np.dot(A,np.linalg.inv(U))
L = np.round(L,0)
L

array([[ 1.,  0.,  0.],
       [ 4.,  1.,  0.],
       [ 7.,  2.,  1.]])

In [40]:
np.dot(L,U)

array([[  1.,   2.,   3.],
       [  4.,   5.,  11.],
       [  7.,   8.,   9.]])

A*transpose(A)  - symetrical matrix.

In [42]:
np.dot(A,np.transpose(A))

array([[ 14,  47,  50],
       [ 47, 162, 167],
       [ 50, 167, 194]])

Transpose(AB) = transpose(B)transpose(A)

In [45]:
np.transpose(np.dot(L,U))

array([[  1.,   4.,   7.],
       [  2.,   5.,   8.],
       [  3.,  11.,   9.]])

In [46]:
np.dot(np.transpose(U),np.transpose(L))

array([[  1.,   4.,   7.],
       [  2.,   5.,   8.],
       [  3.,  11.,   9.]])