In [1]:
import numpy as np

Vector spaces. Starting from Lecture 5

R^2 = all 2-dimensial vectors with Real numbers. [1,2] [Pi,e] etc etc etc

R^3 = all 3-dimensial vectors with Real numbers. [1,2,3] [Pi,e,1.(3)] etc etc etc

R^2, a line through [0,0], a [0,0] itself are subspaces of R^2.

R^3, a plane through [0,0], a line through [0,0], a [0,0] itself are subspaces of R^3.

In [5]:
B = np.array([[1,3],
              [2,3],
              [4,1]])

The subspace of a Matrix above is a plane containing both vectors [1,2,4] [3,3,1] and [0,0,0]. It is called column space.

In [6]:
A = np.array([[1,1,2],
            [2,1,3],
            [3,1,4],
            [4,1,5]])

Ax=b can be solved if b is a vector in A's column space C(A), subspace of R^4

Nullspace of A  = all x to Ax=0. Subspace in R^3

In [12]:
b=np.empty(4)
b

array([  3.49712164e-317,   3.48310470e-316,   1.03565606e-316,
         8.10513562e-315])

Rank of matrix. Ax=0

In [14]:
A = np.array([[1,2,2,2],
             [2,4,6,8],
             [3,6,8,10]])

In [15]:
A2 = np.array([[1,2,2,2],
               [0,0,2,4],
               [0,0,2,4]])

In [26]:
A3 = np.array([[1,2,2,2],
              [0,0,2,4],
              [0,0,0,0]])
U = A3
U

array([[1, 2, 2, 2],
       [0, 0, 2, 4],
       [0, 0, 0, 0]])

2 pivots, means a rank of 2. x1 and x3 - pivot variables.

Variable x2 and x4 are free variables.

In [40]:
r = 2
xn1 = np.array([-2,1,0,0])
xn2 = np.array([2,0,-2,1])
np.dot(A,xn2)

array([0, 0, 0])

Reduced row echelon form. The goal is to have 0s above and below pivots. And make pivots =1.

In [22]:
U2 = np.array([[1,2,0,-2],
             [0,0,2,4],
             [0,0,0,0]])

In [25]:
U3 = np.array([[1,2,0,-2],
              [0,0,1,2],
              [0,0,0,0]])
R = U3
R

array([[ 1,  2,  0, -2],
       [ 0,  0,  1,  2],
       [ 0,  0,  0,  0]])

R = [I,F]
    [0,0]
 pivot free
 
 x = [-F]
     [I ]

Augmented matrix. [A | b]

In [31]:
b = [1,5,6]
Aug = np.c_[A,b]
Aug

array([[ 1,  2,  2,  2,  1],
       [ 2,  4,  6,  8,  5],
       [ 3,  6,  8, 10,  6]])

In [34]:
Uaug = np.c_[U,np.array([b[0],b[1]-2*b[0],b[2]-b[1]-b[0]])]
Uaug


array([[1, 2, 2, 2, 1],
       [0, 0, 2, 4, 3],
       [0, 0, 0, 0, 0]])

Solvable if b is in C(A). If combination of A rows gives 0 row, then the same combination of b entries should give 0.

To find a particular solution a good practice is to assigns 0s to free variable and find unique solution.

Then we find Nullspace solutions.

Final solution will be xp+xn. Axp=b; Axn=0;A(xp+xn)=b - complete solution xc = xp + c1*xn1 + c2*xn2. c - any constants

In [42]:
xc = np.array([-2,0,3/2,0])+xn1+xn2
xc

array([-2. ,  1. , -0.5,  1. ])

If r = n - full column rank, xn - zero vector, thus x = xp, if xp - exists. Hence 0 or 1 solution.

If r=n=m full rank matrix. R = I. Unique solution for any b (1 solution.


If r=m<n R=[IF], 1 or infinite solutions.

If r<m, r<n R =[I/0 F/0] - 0 or infinite solutions.